name: CD - Deploy to GKE

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  CLUSTER: ${{ secrets.GKE_CLUSTER }}
  IMAGE_NAME: iris-api
  USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: gke-gcloud-auth-plugin

    - name: Configure Docker with Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Pull data and model from DVC
      run: |
        pip install dvc dvc-gs
        dvc pull || true

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI="$REGION-docker.pkg.dev/$PROJECT_ID/iris-repo/$IMAGE_NAME:latest"
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER --region $REGION --project $PROJECT_ID

    - name: Deploy to GKE
      run: |
        sed -i "s|<IMAGE_URI>|$IMAGE_URI|" k8s/deployment.yaml
        kubectl apply -f k8s/
